plugins {
	id("org.relativitymc.neo-loom")
	id("multiloader-loader")
}

chenille {
	github = new URL("https://github.com/Ladysnake/${rootProject.name}")
	changelogFile = rootProject.file("changelog.md")
	javaVersion = 25
	configurePublishing {
		withLadysnakeMaven()
		withGithubRelease()
		withModrinthRelease()
		fabricCompatible = true
		neoforgeCompatible = quiltCompatible = false
	}
}
githubRelease.allowUploadToExisting = true

loom {
	def classTweaker = project(":${rootProject.name}-common").file("src/main/resources/${mod_id}.classtweaker")
	if (classTweaker.exists()) {
		accessWidenerPath = classTweaker
	}
	mods {
		register(rootProject.name) {
			sourceSet("main")
			sourceSet(project(":${rootProject.name}-common").sourceSets.main)
		}
	}

	runs {
		fabricApi.configureDataGeneration {
			outputDirectory = project(":${rootProject.name}-common").file("src/main/generated")
			modId = mod_id
			client = true
			addToResources = false
		}
		named("client") {
			configName = "Fabric Client"
		}
		named("server") {
			configName = "Fabric Server"
		}
		named("datagen") {
			configName = "Fabric Datagen"
		}

		configureEach {
			ideConfigGenerated = true
			property("mixin.debug.export", "true")
		}
	}
}

repositories {
	maven {
		name = "TerraformersMC"
		url = "https://maven.gnomecraft.net/releases"
	}
}

dependencies {
	minecraft("com.mojang:minecraft:${minecraft_version}")
	implementation("net.fabricmc:fabric-loader:${loader_version}")

	implementation("net.fabricmc.fabric-api:fabric-api:${fabric_api_version}")
	implementation("moriyashiine.strawberrylib:strawberrylib-fabric:${strawberrylib_version}")

	localRuntime("com.terraformersmc:modmenu:${mod_menu_version}")
}
